### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by lex111** [30-seconds/30-seconds-of-php#3]
For example http://python.kriadmin.me/

Is needed this?

**Comment by peter279k** [comment]
@sohelamin, is any idea about this?

**Comment by sohelamin** [comment]
Hello Guys, I've no plan with this now.
Do you think it is necessary? all the snippets are already documented.

**Comment by peter279k** [comment]
IMHO, it's not necessary for me because the all functions usage are in ```README.md``` as @sohelamin says.

The web document version is an optional work.

**Comment by MetalArend** [comment]
You could add links to https://3v4l.org/ to make examples interactive.

**Comment by Chalarangelo** [comment]
Closing as resolved.
