### ISSUE TITLE
I want to add a string shorten function.

### ISSUE THREAD

**Issue by StyxOfDynamite** [30-seconds/30-seconds-of-php#68]
## Description

I've made a simple function that shortens a string to a given length and appends an optional string to show it's been shortened.

https://3v4l.org/II4aX

I've got the code snippet in a `.md` file but don't know how to test the build process.

https://github.com/StyxOfDynamite/30-seconds-of-php-code/blob/master/snippets/shorten.md

**Comment by peter279k** [comment]
Hi @StyxOfDynamite, thanks for your reply.

Have you read this [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-php/blob/master/CONTRIBUTING.md)?

I think this markdown file will help you to answer your question and accomplish this issue :).

**Comment by StyxOfDynamite** [comment]
@peter279k The [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-php/blob/master/CONTRIBUTING.md) guide is what I followed, but there's no instructions on the actual build process that will generate the top level README.md.

If you look at the snippet I've supplied a link to you can see it fits the required format, I've also provided a test case.

**Comment by peter279k** [comment]
Hi @StyxOfDynamite, I know where the problem is.

We have changed the build snippet processes recently and I also cannot find any test work on Travis CI build.

Let me create a issue to mention that :).

**Comment by StyxOfDynamite** [comment]
@peter279k I've added `UnitTest` and method to `helpers.php` on my fork.

**Comment by peter279k** [comment]
> @peter279k I've added `UnitTest` and method to `helpers.php` on my fork.

I know that, but something are missing after changing into the new build process of code snippets.

You can track this issue #69 and I think we should resolve this issue firstly.

And this issue you create will be resolved.

Anyway, thanks for your contribution again!

**Comment by Chalarangelo** [comment]
New snippets are tested manually from both the contributors and the @30-seconds/php team for now. Testing integration is not yet complete after migrating, but should be up at a later point, presumably. Also building shouldn't be a concern at all, as the main point of the migration was for contributors to be able to add snippets without concerning themselves with the infrastructure.

You can PR this snippet and we will review and merge it, if it follows guidelines and is useful.

@peter279k  #69 will take a lot more work to complete, snippets can be added in the meantime - we don't get 50 snippets a week for manual testing to be infeasible. :wink:

**Comment by StyxOfDynamite** [comment]
Hi all, submitted #70
