### ISSUE TITLE
Why all snippets of this category are some pieces of crap?

### ISSUE THREAD

**Issue by 4n70w4** [30-seconds/30-seconds-of-php#83]
For example https://github.com/30-seconds/30-seconds-of-php/blob/master/snippets/findLast.md

Why does this snippet exist? What is the knowledge here?

**Comment by Chalarangelo** [comment]
Thanks for the feedback. We are constantly working to improve our content and add new snippets. If you have suggestions on how to improve, please submit a PR and we will take care of it.

I am closing and locking due to inappropriate language. Remember, being polite goes a long way. Thank you.
